server {
    listen 8000;

    root /mnt/c/Users/Glenn/Documents/CSUMB/proof-checker/frontend;
    index index.html;

    location /backend/ {
        proxy_set_header Proxy "";
        proxy_pass http://127.0.0.1:8080/;
    }

    location = /checkproof.php {
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /mnt/c/Users/Glenn/Documents/CSUMB/proof-checker/frontend/checkproof.php;
        include fastcgi_params;
    }
}
