server {
    listen 8000;

    root /mnt/c/Users/Glenn/Documents/CSUMB/proof-checker/frontend;
    index index.html;

    location /backend/ {
        proxy_set_header Proxy "";
        proxy_pass http://127.0.0.1:5000/;
    }

    location = /checkproof.php {
        proxy_pass http://127.0.0.1:5000/checkproof;
        proxy_set_header Host $host;
    }
}
